sudo: required
services:
  - docker

branches:
  only:
    - master

env:
  global:
    - DOCKER_IMAGE="mayfieldrobotics/gizmo_base"

notifications:
  email:
    recipients:
      - dev@mayfieldrobotics.com
    on_success: change
    on_failure: change

before_install:
  # https://github.com/travis-ci/travis-ci/issues/5326
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")

install:
  - sudo apt-get install lcov
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
  - docker pull ${DOCKER_IMAGE}:${TRAVIS_BRANCH} || exit 1

script:
  - |
    docker run --rm \
      -e CONTINUOUS_INTEGRATION=${CONTINUOUS_INTEGRATION} \
      -e TRAVIS_BRANCH=${TRAVIS_BRANCH} \
      -v ${TRAVIS_BUILD_DIR}:/root/kuri_edu \
      ${DOCKER_IMAGE}:${TRAVIS_BRANCH} \
      /root/kuri_edu/ci_tools/ci.bash

after_success:
  # - cd ${TRAVIS_BUILD_DIR}
  # - sudo chown -R $(whoami) .
  # - lcov --directory . --capture --output-file coverage_test.info
  # - lcov -a coverage_base.info -a coverage_test.info --output-file coverage_full.info
  # # Remove the base files or codecov will find them
  # - rm coverage_base.info coverage_test.info
  # # Remove coverage from system libs, tests
  # - lcov --extract coverage_full.info '*/mobile_base/*' --output-file coverage_full.info
  # - lcov --remove coverage_full.info '*/test/*' --output-file coverage_full.info
  # - lcov -l coverage_full.info
